participantInfo = struct(...
    'id',               4,...            
    'age',              25,...
    'height',           1.70,...
    'weight',           60,...
    'headCircumference',57,...
    'headWidth',        15.3,...
    'headDepth',        19.5,...
    'headHeight',       18.3,...
    'neckLengthC7Fm',   10.2,...
    'neckLengthSnFm',   16.9,...
    'neckCircumference',35.5,...
    'neckWidth',        10.4,...
    'neckDepth',        10.5,...
    'sex',              'm');
