participantInfo = struct(...
    'id',               6,...            
    'age',              22,...
    'height',           1.72,...
    'weight',           62,...
    'headCircumference',55,...
    'headWidth',        15.4,...
    'headDepth',        17.6,...
    'headHeight',       18.1,...
    'neckLengthC7Fm',   13.6,...
    'neckLengthSnFm',   16.9,...
    'neckCircumference',35.0,...
    'neckWidth',        11.8,...
    'neckDepth',        16.3,...
    'sex',              'm');
