participantInfo = struct(...
    'id',               7,...              
    'age',              19,...
    'height',           1.69,...
    'weight',           57,...
    'headCircumference',57.3,...
    'headWidth',        14.6,...
    'headDepth',        20.2,...
    'headHeight',       18.4,...
    'neckLengthC7Fm',   10.6,...
    'neckLengthSnFm',   20.2,...
    'neckCircumference',32.4,...
    'neckWidth',        10.8,...
    'neckDepth',        11.0,...
    'sex',              'f');
