participantInfo = struct(...
    'id',               13,...              
    'age',              25,...
    'height',           1.75,...
    'weight',           83,...
    'headCircumference',58.,...
    'headWidth',        15.4,...
    'headDepth',        20.6,...
    'headHeight',       20.8,...
    'neckLengthC7Fm',   11.3,...
    'neckLengthSnFm',   16.8,...
    'neckCircumference',40.5,...
    'neckWidth',        11.6,...
    'neckDepth',        11.5,...
    'sex',              'm');
