participantInfo = struct(...
    'id',               11,...              
    'age',              21,...
    'height',           1.80,...
    'weight',           65,...
    'headCircumference',57.5,...
    'headWidth',        15.1,...
    'headDepth',        19.4,...
    'headHeight',       18.5,...
    'neckLengthC7Fm',   12,...
    'neckLengthSnFm',   18.4,...
    'neckCircumference',37,...
    'neckWidth',        10.4,...
    'neckDepth',        10.6,...
    'sex',              'm');
