participantInfo = struct(...
    'id',               12,...              
    'age',              23,...
    'height',           1.63,...
    'weight',           45,...
    'headCircumference',51.7,...
    'headWidth',        14.9,...
    'headDepth',        18.4,...
    'headHeight',       16.7,...
    'neckLengthC7Fm',   12.3,...
    'neckLengthSnFm',   20.2,...
    'neckCircumference',28,...
    'neckWidth',        9.3,...
    'neckDepth',        8.5,...
    'sex',              'f');
