function [biopacSignalIntervals,indexSubplot, figOnset] ...
                = extractActiveEMGIntervals(...                       
                        timeV,...
                        carBiopacData,... 
                        biopacSignalIntervals,...
                        onsetDetectionSettings,...
                        biopacIndices,...  
                        biopacKeywords,...
                        biopacParameters,...
                        flag_plotOnset,...
                        indexSubplot,...
                        subPlotPanel,...
                        colorOnset,...                        
                        figOnset)

for i=1:1:size(carBiopacData.labels,1)
    if(contains(carBiopacData.labels(i,:),biopacKeywords.emg))


        assert(isempty(biopacSignalIntervals(biopacIndices.indexAccCarX).intervalIndices)==0,...
                   ['Error: The car did not accelerate. The code should not be able to',...
                     ' evaluate the EMG onsets']);

        %Get the acceleration window associated with both the car
        %and the head.


        indexAccMin = min(biopacSignalIntervals(biopacIndices.indexAccCarX).intervalIndices(1,:));
        indexAccMax = max(biopacSignalIntervals(biopacIndices.indexAccCarX).intervalIndices(1,:));                

        %If the head also moves, include its movement in definining
        %the minimum and maximum times.
        if(isempty(biopacSignalIntervals(biopacIndices.indexAccHeadX).intervalIndices)==0)
            indexAccMin = ...
                min( biopacSignalIntervals(biopacIndices.indexAccCarX).intervalIndices(1,:),...
                     biopacSignalIntervals(biopacIndices.indexAccHeadX).intervalIndices(1,:));
    
            indexAccMax = ...
                max( biopacSignalIntervals(biopacIndices.indexAccCarX).intervalIndices(1,:),...
                     biopacSignalIntervals(biopacIndices.indexAccHeadX).intervalIndices(1,:));
        end

        timeAccMin = timeV(indexAccMin,1);
        timeAccMax = timeV(indexAccMax,1);        
        timeWindowStart = timeAccMin+onsetDetectionSettings.minimumAcceptableOnsetTime;
        timeWindowEnd   = timeAccMax+onsetDetectionSettings.maximumAcceptableOnsetTime; 
        timeWindowEnd   = min(max(timeV),timeWindowEnd);


        signalWindowIndices = ...
            [timeWindowStart,timeWindowEnd].*biopacParameters.sampleFrequencyHz;

        signalWindowIndices = round(signalWindowIndices);

        noiseWindowIndices = [1,round(indexAccMin*0.95)];

        flag_plotOnsetAlgorithmDetails=0;

        [peakIntervalRaw,...
         peakIntervalFiltered, ...
         noiseBlocks,...
         dataZeroMedian,...
         dataZeroMedianFiltered] = ...
            findOnsetUsingNoiseModel(...
                carBiopacData.data(:,i), ...
                signalWindowIndices,...
                noiseWindowIndices,...
                onsetDetectionSettings.numberOfNoiseSubWindows,...
                onsetDetectionSettings.maxAcceptableNoiseProbability,...
                onsetDetectionSettings.minimumTimingGap,...
                onsetDetectionSettings.lowFrequencyFilterCutoff,...
                biopacParameters.sampleFrequencyHz,...
                onsetDetectionSettings.typeOfNoiseModel,...
                flag_plotOnsetAlgorithmDetails);


        if(isempty(peakIntervalRaw)==0)
            biopacSignalIntervals(i).intervalIndices   = ...
                [peakIntervalRaw(1,:)];
            biopacSignalIntervals(i).intervalTimes   = ...
                timeV(peakIntervalRaw(1,:)')';

            if(isempty(peakIntervalRaw)==0)
                i0 = peakIntervalRaw(1,1);
                i1 = peakIntervalRaw(1,2);
                biopacSignalIntervals(i).intervalMaximumValue = ...
                    max(abs(carBiopacData.data(i0:1:i1,i)));
            end
        end

        if(flag_plotOnset)
            dataLabel = carBiopacData.labels(i,:);
            dataLabel = dataLabel(1,1:max(30,length(dataLabel)));

            figure(figOnset);
            maxPlotCols = size(subPlotPanel,2);
            maxPlotRows = size(subPlotPanel,1);
            
            row = ceil(indexSubplot/maxPlotCols);
            col = max(1,indexSubplot-(row-1)*maxPlotCols);
            
            subplot('Position',reshape(subPlotPanel(row,col,:),1,4));  

            [figOnset,indexSubplot] = ...                        
                addOnsetPlot(   timeV, ...
                                dataZeroMedian,...
                                dataZeroMedianFiltered,...
                                signalWindowIndices,...
                                noiseBlocks,...
                                peakIntervalFiltered,...
                                colorOnset,...
                                dataLabel,...
                                figOnset, ...
                                subPlotPanel, ...
                                indexSubplot);   

            here=1;

        end
    end

end