function labelledMarkerData= ...
    renameLabelledMarkerData(labelledMarkerData,...
                parentName,markerName,newMarkerName)

%Rename the markers
for indexMarker=1:1:length(labelledMarkerData)
    for indexRename = 1:1:length(newMarkerName)
        if(   contains(labelledMarkerData(indexMarker).markerName, ...
                       parentName{indexRename}) ...
           && contains(labelledMarkerData(indexMarker).markerName,...
                       markerName{indexRename}))

            labelledMarkerData(indexMarker).markerName = ...
                newMarkerName{indexRename};
                                        
        end
    end
end