function rigidBodyMarkerData= ...
    renameRigidBodyMarkers(rigidBodyMarkerData,...
                parentName,markerName,newMarkerName)

%Rename the markers
for indexMarker=1:1:length(rigidBodyMarkerData)
    for indexRename = 1:1:length(newMarkerName)
        if(   contains(rigidBodyMarkerData(indexMarker).parentName, ...
                       parentName{indexRename}) ...
           && contains(rigidBodyMarkerData(indexMarker).markerName,...
                       markerName{indexRename}))

            rigidBodyMarkerData(indexMarker).markerName = ...
                newMarkerName{indexRename};
                                        
        end
    end
end