function [biopacParameters, biopacKeywords, ...
		  biopacChannels, biopacIndices] = getBiopacMetaData()


    biopacParameters.sampleFrequencyHz=2000;%Hz

    biopacKeywords.emg      = 'EMG100C';
	biopacKeywords.ecg      = 'ECG';
	biopacKeywords.accCar   = '- TSD109C -';
	biopacKeywords.accHead  = '- TSD109C2 / TSD109C3 -';
	biopacKeywords.trigger  = 'Trigger';
	biopacKeywords.loadcell = 'loadcell';
	biopacKeywords.force    = 'Force';
    


    biopacChannels = {...
      'STR_L',...                                              
      'STR_R',...                                              
      'TRO_L',...                                              
      'TRO_R',...                                              
      'TRU_L',...                                              
      'TRU_R',...                                              
      'ECG'  ,...                                              
      'Ax - TSD109C',...             
      'Ay - TSD109C',...             
      'Az - TSD109C',...             
      'Force loadcell',...                     
      'ax2 - TSD109C2',...
      'ay2 - TSD109C2',...
      'az2 - TSD109C2',...
      'Trigger - Custom',...                            
      'Force in N'};
    
    biopacIndices = struct(...
      'indexSTR_L',0,...                                              
      'indexSTR_R',0,...                                              
      'indexTRO_L',0,...                                              
      'indexTRO_R',0,...                                              
      'indexTRU_L',0,...                                              
      'indexTRU_R',0,...                                              
      'indexECG'  ,0,...                                              
      'indexAccCarX',0,...             
      'indexAccCarY',0,...             
      'indexAccCarZ',0,...             
      'indexLoadCell',0,...                     
      'indexAccHeadX',0,...
      'indexAccHeadY',0,...
      'indexAccHeadZ',0,...
      'indexTrigger',0,...                            
      'indexForce',0);