function participantData=...
     getParticipantDataMay2022(participantId)


participantData = [];




switch participantId
    case 1
        participantData = struct(...
            'id',               participantId,...              
            'age',              29,...
            'height',           1.74,...
            'weight',           74,...
            'headCircumference',60,...
            'headWidth',        15.9,...
            'headDepth',        21.2,...
            'headHeight',       20,...
            'neckLengthC7Fm',   9.6,...
            'neckLengthSnFm',   18.8,...
            'neckCircumference',37.2,...
            'neckWidth',        10,...
            'neckDepth',        10.5,...
            'sex',              'm');   

    case 2
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
   
    case 3
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
    
    case 4
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 5
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 6
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
        
    case 7 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
            

    case 8 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 9
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
  
    case 10            
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 11
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 12
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   


    case 13 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 14 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   

    case 15 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);                    
           
    case 16 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);            

    case 17 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);

    case 18 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);    

    case 19 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);  

    case 20 
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);                             

    case 21
        participantData = struct(...
            'id',               participantId,...              
            'age',              nan,...
            'height',           nan,...
            'weight',           nan,...
            'headCircumference',nan,...
            'headWidth',        nan,...
            'headDepth',        nan,...
            'headHeight',       nan,...
            'neckLengthC7Fm',   nan,...
            'neckLengthSnFm',   nan,...
            'neckCircumference',nan,...
            'neckWidth',        nan,...
            'neckDepth',        nan,...
            'sex',              nan);   
            disp(sprintf('Warning: participant %i information not filled');         

    otherwise
        assert(0, ['Error: particpantId is not within the range of 1-21,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end