function participantCarData=...
     getParticipantCarDataFebruary2023(participantId)


participantCarData = [];





switch participantId
    case 1
        participantCarData.id           = participantId;

        participantCarData.condition       = {'nominal'; ...
                                              'nominal';...
                                              'seatBack'};

        %From the back of the hand-written paper sheet
        participantCarData.block           = {'headRom';...
                                              'A';...
                                              'B'};

        %These are the start and end file numbers for each of the
        %the conditions listed above
        participantCarData.blockFileNumbers = [8, 8;...
                                               9, 20;...
                                               21,27];

        %If the notes mention to ignore a trial that is within
        %the range in conditionFileNumbers, list them here.                                          
        participantCarData.ignoreTheseFileNumbers = [];                                           


    case 2
        participantCarData.id               = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];
        
    case 3
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 4
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 5
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 6
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 7 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 8 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 9
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];


    case 10   
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 11
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 12
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 13 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 14 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 15 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];
    case 16 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];
    case 17 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];


    case 18 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 19 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 20 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];
    case 21
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 22
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 23 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 24 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 25 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 26 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];


    case 27 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];
    case 28 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                '-';...
                                                '-'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

   otherwise
        assert(0, ['Error: particpantId is not within the range of 1-28,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end