function participantCarData=...
     getParticipantCarDataMay2022(participantId)


participantCarData = [];
participantCarData.biopacProblems = [];
participantCarData.ignoreTheseFileNumbers = [];

%If the notes mention EMG problems, please enter these problems into the 
%biopacProblemsStruct like this:
%
% Trial 11 has EMG problems on channels 2 and 3
% Trial 12 has EMG problems on channels 1
%
% We have 2 problematic trials, so we need an array of 2 biopacProblemsStruct:
%
%       biopacProblemsStruct(2) = struct('trialNumber',0,'channels',[]);
%
% And we fill out the struct like this
%
%       biopacProblemsStruct(1).trialNumber = 11;
%       biopacProblemsStruct(1).channels    = [2,3];
%       biopacProblemsStruct(2).trialNumber = 12;
%       biopacProblemsStruct(2).channels    = [1];
%
% Then we put this information into the participant struct like this:
%
%       participantCarData.biopacProblems = biopacProblemsStruct;
%






switch participantId
    case 1
        participantCarData.id           = participantId;

        participantCarData.condition       = {'nominal'; ...
                                              'nominal';...
                                              'headTurned'};

        %From the back of the hand-written paper sheet
        participantCarData.block           = {'headRom';...
                                              'A';...
                                              'B'};

        %These are the start and end file numbers for each of the
        %the conditions listed above
        participantCarData.blockFileNumbers = [5, 5;...
                                               10, 22;...
                                               23,30];

        %If the notes mention to ignore a trial that is within
        %the range in conditionFileNumbers, list them here.                                          
        participantCarData.ignoreTheseFileNumbers = [];                                           


    case 2
        participantCarData.id               = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 1, 1;...
                                                2, 13;...
                                                14, 21];
        participantCarData.ignoreTheseFileNumbers = [];
        
    case 3
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 7, 7;...
                                                8, 19;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 4
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                0, 0;...
                                                0, 0];
        participantCarData.ignoreTheseFileNumbers = [];

    case 5
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 8, 8;...
                                                9, 29;...
                                                30, 37];
        participantCarData.ignoreTheseFileNumbers = [15, 19, 20 , 21, 22, 23, 24, 25, 26];

    case 6
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                4, 15;...
                                                16, 23];
        participantCarData.ignoreTheseFileNumbers = [];

    case 7 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                5, 16;...
                                                17, 24];
        participantCarData.ignoreTheseFileNumbers = [];

    case 8 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                7, 18;...
                                                19, 26];
        participantCarData.ignoreTheseFileNumbers = [];

    case 9
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                6, 17;...
                                                18, 25];
        participantCarData.ignoreTheseFileNumbers = [];


    case 10   
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                7, 18;...
                                                19, 26];
        participantCarData.ignoreTheseFileNumbers = [];

    case 11
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                4, 15;...
                                                16, 23];
        participantCarData.ignoreTheseFileNumbers = [];

    case 12
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                9, 23;...
                                                24, 31];
        participantCarData.ignoreTheseFileNumbers = [17, 21, 22];

    case 13 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                7, 18;...
                                                26, 33];
        participantCarData.ignoreTheseFileNumbers = [];

    case 14 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                8, 19;...
                                                20, 27];
        participantCarData.ignoreTheseFileNumbers = [];

    case 15 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 1, 1;...
                                                2, 13;...
                                                14, 21];
        participantCarData.ignoreTheseFileNumbers = [];
    case 16 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                5, 16;...
                                                24, 31];
        participantCarData.ignoreTheseFileNumbers = [];
    case 17 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                5, 16;...
                                                17, 24];
        participantCarData.ignoreTheseFileNumbers = [];


    case 18 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                4, 15;...
                                                16, 23];
        participantCarData.ignoreTheseFileNumbers = [];

    case 19 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                6, 17;...
                                                18, 25];
        participantCarData.ignoreTheseFileNumbers = [];

    case 20 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'C'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                4, 15;...
                                                16, 23];
        participantCarData.ignoreTheseFileNumbers = [];
    case 21
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'headTurned'};        
        participantCarData.block            = { 'headRom';...
                                                'B';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 0, 0;...
                                                4, 12;...
                                                16, nan];
        participantCarData.ignoreTheseFileNumbers = [];
    

   otherwise
        assert(0, ['Error: particpantId is not within the range of 1-21,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end