function participantData=...
     getParticipantDataMay2022(participantId)


participantData = [];




switch participantId
    case 1
        participantData = struct(...
            'id',               participantId,...              
            'age',              29,...
            'height',           174,...
            'weight',           74,...
            'headCircumference',60,...
            'headWidth',        15.9,...
            'headDepth',        21.2,...
            'headHeight',       20,...
            'neckLengthC7Fm',   9.6,...
            'neckLengthSnFm',   18.8,...
            'neckCircumference',37.2,...
            'neckWidth',        10,...
            'neckDepth',        10.5,...
            'sex',              'm');   

    case 2
        participantData = struct(...
            'id',               participantId,...              
            'age',              29,...
            'height',           170,...
            'weight',           70,...
            'headCircumference',56,...
            'headWidth',        14.7,...
            'headDepth',        19.7,...
            'headHeight',       18,...
            'neckLengthC7Fm',   11.6,...
            'neckLengthSnFm',   18.21,...
            'neckCircumference',37,...
            'neckWidth',        10.4,...
            'neckDepth',        9.9,...
            'sex',              'm');   
   
    case 3
        participantData = struct(...
            'id',               participantId,...              
            'age',              20,...
            'height',           165,...
            'weight',           67,...
            'headCircumference',56.3,...
            'headWidth',        14.7,...
            'headDepth',        18.9,...
            'headHeight',       17.1,...
            'neckLengthC7Fm',   9,...
            'neckLengthSnFm',   17,...
            'neckCircumference',35,...
            'neckWidth',        10.1,...
            'neckDepth',        10.2,...
            'sex',              'f');   
    
    case 4
        participantData = struct(...
            'id',               participantId,...              
            'age',              24,...
            'height',           183,...
            'weight',           80,...
            'headCircumference',57,...
            'headWidth',        15.5,...
            'headDepth',        21,...
            'headHeight',       18.5,...
            'neckLengthC7Fm',   13.4,...
            'neckLengthSnFm',   19.4,...
            'neckCircumference',41,...
            'neckWidth',        12.5,...
            'neckDepth',        12.2,...
            'sex',              'm');   

    case 5
        participantData = struct(...
            'id',               participantId,...              
            'age',              20,...
            'height',           177,...
            'weight',           71,...
            'headCircumference',57.5,...
            'headWidth',        15.4,...
            'headDepth',        19.3,...
            'headHeight',       18.5,...
            'neckLengthC7Fm',   12.4,...
            'neckLengthSnFm',   17.5,...
            'neckCircumference',34,...
            'neckWidth',        10.7,...
            'neckDepth',        8.9,...
            'sex',              'f');   

    case 6
        participantData = struct(...
            'id',               participantId,...              
            'age',              20,...
            'height',           183,...
            'weight',           82,...
            'headCircumference',56.6,...
            'headWidth',        15,...
            'headDepth',        19.7,...
            'headHeight',       19.7,...
            'neckLengthC7Fm',   9.7,...
            'neckLengthSnFm',   15.4,...
            'neckCircumference',39.4,...
            'neckWidth',        11.5,...
            'neckDepth',        10.6,...
            'sex',              'm');   
        
    case 7 
        participantData = struct(...
            'id',               participantId,...              
            'age',              26,...
            'height',           172,...
            'weight',           63,...
            'headCircumference',55,...
            'headWidth',        14.7,...
            'headDepth',        18.9,...
            'headHeight',       18,...
            'neckLengthC7Fm',   8.8,...
            'neckLengthSnFm',   18.1,...
            'neckCircumference',31.6,...
            'neckWidth',        9.7,...
            'neckDepth',        9.1,...
            'sex',              'f');   
            

    case 8 
        participantData = struct(...
            'id',               participantId,...              
            'age',              23,...
            'height',           183,...
            'weight',           76,...
            'headCircumference',55.6,...
            'headWidth',        14.8,...
            'headDepth',        19.7,...
            'headHeight',       17.7,...
            'neckLengthC7Fm',   10.7,...
            'neckLengthSnFm',   18.3,...
            'neckCircumference',34.8,...
            'neckWidth',        10.4,...
            'neckDepth',        10.4,...
            'sex',              'm');   

    case 9
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           169,...
            'weight',           60,...
            'headCircumference',56,...
            'headWidth',        15,...
            'headDepth',        19.4,...
            'headHeight',       17.1,...
            'neckLengthC7Fm',   12.5,...
            'neckLengthSnFm',   18,...
            'neckCircumference',31.6,...
            'neckWidth',        10.4,...
            'neckDepth',        8.6,...
            'sex',              'f');   
  
    case 10            
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           165,...
            'weight',           50,...
            'headCircumference',53.2,...
            'headWidth',        13.6,...
            'headDepth',        19.1,...
            'headHeight',       18,...
            'neckLengthC7Fm',   9.2,...
            'neckLengthSnFm',   16,...
            'neckCircumference',30,...
            'neckWidth',        8.8,...
            'neckDepth',        8.2,...
            'sex',              'f');   

    case 11
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           184,...
            'weight',           72,...
            'headCircumference',58.4,...
            'headWidth',        14.5,...
            'headDepth',        20.7,...
            'headHeight',       18.5,...
            'neckLengthC7Fm',   13.2,...
            'neckLengthSnFm',   19.7,...
            'neckCircumference',36.2,...
            'neckWidth',        10.7,...
            'neckDepth',        10.4,...
            'sex',              'm');   

    case 12
        participantData = struct(...
            'id',               participantId,...              
            'age',              20,...
            'height',           163,...
            'weight',           60,...
            'headCircumference',54,...
            'headWidth',        14.2,...
            'headDepth',        19.1,...
            'headHeight',       18.9,...
            'neckLengthC7Fm',   10.6,...
            'neckLengthSnFm',   14.5,...
            'neckCircumference',34,...
            'neckWidth',        9.9,...
            'neckDepth',        9.1,...
            'sex',              'f');   


    case 13 
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           177,...
            'weight',           62,...
            'headCircumference',55,...
            'headWidth',        15.4,...
            'headDepth',        20,...
            'headHeight',       18.6,...
            'neckLengthC7Fm',   10.8,...
            'neckLengthSnFm',   18,...
            'neckCircumference',35.6,...
            'neckWidth',        10.5,...
            'neckDepth',        10,...
            'sex',              'f');   

    case 14 
        participantData = struct(...
            'id',               participantId,...              
            'age',              24,...
            'height',           158,...
            'weight',           56,...
            'headCircumference',53.5,...
            'headWidth',        14.7,...
            'headDepth',        18.2,...
            'headHeight',       16.7,...
            'neckLengthC7Fm',   11,...
            'neckLengthSnFm',   14.6,...
            'neckCircumference',30.6,...
            'neckWidth',        9.2,...
            'neckDepth',        9,...
            'sex',              'f');   

    case 15 
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           172,...
            'weight',           56,...
            'headCircumference',55,...
            'headWidth',        14.6,...
            'headDepth',        19.2,...
            'headHeight',       17.4,...
            'neckLengthC7Fm',   10.7,...
            'neckLengthSnFm',   19,...
            'neckCircumference',34,...
            'neckWidth',        9.4,...
            'neckDepth',        8.6,...
            'sex',              'f');                    
           
    case 16 
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           172,...
            'weight',           70,...
            'headCircumference',56,...
            'headWidth',        16.1,...
            'headDepth',        18.7,...
            'headHeight',       18.5,...
            'neckLengthC7Fm',   10.5,...
            'neckLengthSnFm',   17.5,...
            'neckCircumference',37,...
            'neckWidth',        10.7,...
            'neckDepth',        10.6,...
            'sex',              'm');            

    case 17 
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           170,...
            'weight',           70,...
            'headCircumference',56,...
            'headWidth',        15.2,...
            'headDepth',        19.2,...
            'headHeight',       19.5,...
            'neckLengthC7Fm',   10.9,...
            'neckLengthSnFm',   17.3,...
            'neckCircumference',35,...
            'neckWidth',        9.6,...
            'neckDepth',        9.8,...
            'sex',              'f');

    case 18 
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           174,...
            'weight',           68,...
            'headCircumference',55.5,...
            'headWidth',        15,...
            'headDepth',        19.6,...
            'headHeight',       18.7,...
            'neckLengthC7Fm',   10.4,...
            'neckLengthSnFm',   17.8,...
            'neckCircumference',34,...
            'neckWidth',        10.4,...
            'neckDepth',        10.5,...
            'sex',              'f');    

    case 19 
        participantData = struct(...
            'id',               participantId,...              
            'age',              23,...
            'height',           180,...
            'weight',           75,...
            'headCircumference',59,...
            'headWidth',        15.8,...
            'headDepth',        21,...
            'headHeight',       19.4,...
            'neckLengthC7Fm',   12.5,...
            'neckLengthSnFm',   19.1,...
            'neckCircumference',37.8,...
            'neckWidth',        10.5,...
            'neckDepth',        10.6,...
            'sex',              'm');  

    case 20 
        participantData = struct(...
            'id',               participantId,...              
            'age',              23,...
            'height',           180,...
            'weight',           80,...
            'headCircumference',58.6,...
            'headWidth',        15.7,...
            'headDepth',        20.6,...
            'headHeight',       18.9,...
            'neckLengthC7Fm',   11.2,...
            'neckLengthSnFm',   17.2,...
            'neckCircumference',41,...
            'neckWidth',        12.1,...
            'neckDepth',        11,...
            'sex',              'm');                             

    case 21
        participantData = struct(...
            'id',               participantId,...              
            'age',              19,...
            'height',           181,...
            'weight',           68,...
            'headCircumference',57,...
            'headWidth',        15.4,...
            'headDepth',        19.6,...
            'headHeight',       18.1,...
            'neckLengthC7Fm',   9.4,...
            'neckLengthSnFm',   19.5,...
            'neckCircumference',35,...
            'neckWidth',        10.5,...
            'neckDepth',        9.9,...
            'sex',              'f');   
                    

    otherwise
        assert(0, ['Error: particpantId is not within the range of 1-21,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end