function participantData=...
     getParticipantDataFebruary2023(participantId)


participantData = [];


switch participantId
    case 1
        participantData = struct(...
            'id',               participantId,...
            'age',              20,...
            'height',           1.66,...
            'weight',           60,...
            'headCircumference',59,...
            'headWidth',        15.3,...
            'headDepth',        19.2,...
            'headHeight',       20.7,...
            'neckLengthC7Fm',   12.9,...
            'neckLengthSnFm',   18,...
            'neckCircumference',36.7,...
            'neckWidth',        11,...
            'neckDepth',        10.6,...
            'sex',              'm');
    case 2
        participantData = struct(...
            'id',               participantId,...
            'age',              24,...
            'height',           1.72,...
            'weight',           60,...
            'headCircumference',57.5,...
            'headWidth',        15.5,...
            'headDepth',        19.4,...
            'headHeight',       18.6,...
            'neckLengthC7Fm',   13.2,...
            'neckLengthSnFm',   16.5,...
            'neckCircumference',30.6,...
            'neckWidth',        10.4,...
            'neckDepth',        9.3,...
            'sex',              'f');   
    case 3
        participantData = struct(...
            'id',               participantId,...            
            'age',              31,...
            'height',           1.84,...
            'weight',           86,...
            'headCircumference',58,...
            'headWidth',        15.9,...
            'headDepth',        19.8,...
            'headHeight',       19.8,...
            'neckLengthC7Fm',   9.4,...
            'neckLengthSnFm',   19.1,...
            'neckCircumference',38.0,...
            'neckWidth',        11.9,...
            'neckDepth',        12.1,...
            'sex',              'm');    
    case 4
        participantData = struct(...
            'id',               participantId,...            
            'age',              25,...
            'height',           1.70,...
            'weight',           60,...
            'headCircumference',57,...
            'headWidth',        15.3,...
            'headDepth',        19.5,...
            'headHeight',       18.3,...
            'neckLengthC7Fm',   10.2,...
            'neckLengthSnFm',   16.9,...
            'neckCircumference',35.5,...
            'neckWidth',        10.4,...
            'neckDepth',        10.5,...
            'sex',              'm');
    case 5
        participantData = struct(...
            'id',               participantId,...            
            'age',              32,...
            'height',           1.74,...
            'weight',           72,...
            'headCircumference',57,...
            'headWidth',        15.4,...
            'headDepth',        19.5,...
            'headHeight',       18.6,...
            'neckLengthC7Fm',   9.2,...
            'neckLengthSnFm',   15.6,...
            'neckCircumference',38.0,...
            'neckWidth',        10.7,...
            'neckDepth',        10.6,...
            'sex',              'm');
    case 6
        participantData = struct(...
            'id',               participantId,...            
            'age',              22,...
            'height',           1.72,...
            'weight',           62,...
            'headCircumference',55,...
            'headWidth',        15.4,...
            'headDepth',        17.6,...
            'headHeight',       18.1,...
            'neckLengthC7Fm',   13.6,...
            'neckLengthSnFm',   16.9,...
            'neckCircumference',35.0,...
            'neckWidth',        11.8,...
            'neckDepth',        16.3,...
            'sex',              'm');        
    case 7 
        participantData = struct(...
            'id',               participantId,...              
            'age',              19,...
            'height',           1.69,...
            'weight',           57,...
            'headCircumference',57.3,...
            'headWidth',        14.6,...
            'headDepth',        20.2,...
            'headHeight',       18.4,...
            'neckLengthC7Fm',   10.6,...
            'neckLengthSnFm',   20.2,...
            'neckCircumference',32.4,...
            'neckWidth',        10.8,...
            'neckDepth',        11.0,...
            'sex',              'f');            

    case 8 
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           1.76,...
            'weight',           70,...
            'headCircumference',55.5,...
            'headWidth',        15.1,...
            'headDepth',        19.5,...
            'headHeight',       20,...
            'neckLengthC7Fm',   13,...
            'neckLengthSnFm',   19.4,...
            'neckCircumference',36.5,...
            'neckWidth',        11.6,...
            'neckDepth',        10.4,...
            'sex',              'm');
    case 9
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.85,...
            'weight',           75,...
            'headCircumference',56.5,...
            'headWidth',        14.8,...
            'headDepth',        18.1,...
            'headHeight',       20.6,...
            'neckLengthC7Fm',   12.3,...
            'neckLengthSnFm',   18.9,...
            'neckCircumference',39.0,...
            'neckWidth',        10.9,...
            'neckDepth',        11,...
            'sex',              'm');  
    case 10            
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.80,...
            'weight',           85,...
            'headCircumference',61,...
            'headWidth',        16,...
            'headDepth',        21,...
            'headHeight',       22.1,...
            'neckLengthC7Fm',   13,...
            'neckLengthSnFm',   20,...
            'neckCircumference',40.8,...
            'neckWidth',        12.3,...
            'neckDepth',        12.1,...
            'sex',              'm');
    case 11
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           1.80,...
            'weight',           65,...
            'headCircumference',57.5,...
            'headWidth',        15.1,...
            'headDepth',        19.4,...
            'headHeight',       18.5,...
            'neckLengthC7Fm',   12,...
            'neckLengthSnFm',   18.4,...
            'neckCircumference',37,...
            'neckWidth',        10.4,...
            'neckDepth',        10.6,...
            'sex',              'm');
    case 12
        participantData = struct(...
            'id',               participantId,...              
            'age',              23,...
            'height',           1.63,...
            'weight',           45,...
            'headCircumference',51.7,...
            'headWidth',        14.9,...
            'headDepth',        18.4,...
            'headHeight',       16.7,...
            'neckLengthC7Fm',   12.3,...
            'neckLengthSnFm',   20.2,...
            'neckCircumference',28,...
            'neckWidth',        9.3,...
            'neckDepth',        8.5,...
            'sex',              'f');

    case 13 
        participantData = struct(...
            'id',               participantId,...              
            'age',              25,...
            'height',           1.75,...
            'weight',           83,...
            'headCircumference',58.,...
            'headWidth',        15.4,...
            'headDepth',        20.6,...
            'headHeight',       20.8,...
            'neckLengthC7Fm',   11.3,...
            'neckLengthSnFm',   16.8,...
            'neckCircumference',40.5,...
            'neckWidth',        11.6,...
            'neckDepth',        11.5,...
            'sex',              'm');

    case 14 
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           1.72,...
            'weight',           56,...
            'headCircumference',53.5,...
            'headWidth',        14,...
            'headDepth',        18.7,...
            'headHeight',       19,...
            'neckLengthC7Fm',   12.4,...
            'neckLengthSnFm',   17.8,...
            'neckCircumference',32.5,...
            'neckWidth',        9.1,...
            'neckDepth',        9.1,...
            'sex',              'f');   

    case 15 
        participantData = struct(...
            'id',               participantId,...              
            'age',              27,...
            'height',           1.75,...
            'weight',           67,...
            'headCircumference',56,...
            'headWidth',        14.6,...
            'headDepth',        19.1,...
            'headHeight',       19.7,...
            'neckLengthC7Fm',   12,...
            'neckLengthSnFm',   16.6,...
            'neckCircumference',31.5,...
            'neckWidth',        9.9,...
            'neckDepth',        9.8,...
            'sex',              'f');      
           
    case 16 
        participantData = struct(...
            'id',               participantId,...              
            'age',              23,...
            'height',           1.68,...
            'weight',           55,...
            'headCircumference',54,...
            'headWidth',        14.4,...
            'headDepth',        20.5,...
            'headHeight',       20.4,...
            'neckLengthC7Fm',   11.3,...
            'neckLengthSnFm',   20.9,...
            'neckCircumference',31.4,...
            'neckWidth',        10.4,...
            'neckDepth',        10.9,...
            'sex',              'f');            

    case 17 
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.69,...
            'weight',           60,...
            'headCircumference',54.6,...
            'headWidth',        14.7,...
            'headDepth',        20.8,...
            'headHeight',       19.7,...
            'neckLengthC7Fm',   12.4,...
            'neckLengthSnFm',   20.5,...
            'neckCircumference',32.7,...
            'neckWidth',        10.3,...
            'neckDepth',        9.4,...
            'sex',              'f');

    case 18 
        participantData = struct(...
            'id',               participantId,...              
            'age',              25,...
            'height',           1.79,...
            'weight',           65,...
            'headCircumference',56.5,...
            'headWidth',        16.6,...
            'headDepth',        18.8,...
            'headHeight',       19.9,...
            'neckLengthC7Fm',   13.4,...
            'neckLengthSnFm',   18.8,...
            'neckCircumference',35.3,...
            'neckWidth',        11.8,...
            'neckDepth',        10.9,...
            'sex',              'm');    

    case 19 
        participantData = struct(...
            'id',               participantId,...              
            'age',              21,...
            'height',           1.96,...
            'weight',           96,...
            'headCircumference',62,...
            'headWidth',        17.1,...
            'headDepth',        20.1,...
            'headHeight',       22.7,...
            'neckLengthC7Fm',   12.8,...
            'neckLengthSnFm',   19.2,...
            'neckCircumference',42.5,...
            'neckWidth',        12.3,...
            'neckDepth',        11.8,...
            'sex',              'm');  

    case 20 
        participantData = struct(...
            'id',               participantId,...              
            'age',              27,...
            'height',           1.78,...
            'weight',           64,...
            'headCircumference',56.5,...
            'headWidth',        15.3,...
            'headDepth',        20.4,...
            'headHeight',       19.8,...
            'neckLengthC7Fm',   12.1,...
            'neckLengthSnFm',   18.6,...
            'neckCircumference',34,...
            'neckWidth',        10.7,...
            'neckDepth',        10.4,...
            'sex',              'f');       

    case 21
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.69,...
            'weight',           60,...
            'headCircumference',55.5,...
            'headWidth',        14.5,...
            'headDepth',        19.7,...
            'headHeight',       19.6,...
            'neckLengthC7Fm',   10.6,...
            'neckLengthSnFm',   20.4,...
            'neckCircumference',31.3,...
            'neckWidth',        9.5,...
            'neckDepth',        10.1,...
            'sex',              'f');   

    case 22
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.77,...
            'weight',           62,...
            'headCircumference',57,...
            'headWidth',        15.4,...
            'headDepth',        19.1,...
            'headHeight',       20.3,...
            'neckLengthC7Fm',   11.1,...
            'neckLengthSnFm',   19.2,...
            'neckCircumference',36,...
            'neckWidth',        10.7,...
            'neckDepth',        10.4,...
            'sex',              'f');   

    case 23 
        participantData = struct(...
            'id',               participantId,...              
            'age',              22,...
            'height',           1.82,...
            'weight',           65,...
            'headCircumference',58,...
            'headWidth',        15.3,...
            'headDepth',        19.8,...
            'headHeight',       19.5,...
            'neckLengthC7Fm',   13.6,...
            'neckLengthSnFm',   17.1,...
            'neckCircumference',32.5,...
            'neckWidth',        10,...
            'neckDepth',        10.1,...
            'sex',              'f');   

    case 24 
        participantData = struct(...
            'id',               participantId,...              
            'age',              20,...
            'height',           1.81,...
            'weight',           87,...
            'headCircumference',58,...
            'headWidth',        15.3,...
            'headDepth',        20.4,...
            'headHeight',       10.1,...
            'neckLengthC7Fm',   11.9,...
            'neckLengthSnFm',   16.7,...
            'neckCircumference',39,...
            'neckWidth',        11.1,...
            'neckDepth',        11.8,...
            'sex',              'm');   

    case 25 
        participantData = struct(...
            'id',               participantId,...              
            'age',              27,...
            'height',           1.8,...
            'weight',           68,...
            'headCircumference',57,...
            'headWidth',        15.7,...
            'headDepth',        19.4,...
            'headHeight',       19.5,...
            'neckLengthC7Fm',   11.8,...
            'neckLengthSnFm',   19.3,...
            'neckCircumference',37,...
            'neckWidth',        11.7,...
            'neckDepth',        11.5,...
            'sex',              'm');                    
           
    case 26 
        participantData = struct(...
            'id',               participantId,...              
            'age',              25,...
            'height',           1.73,...
            'weight',           57,...
            'headCircumference',55.2,...
            'headWidth',        15,...
            'headDepth',        19.5,...
            'headHeight',       19.4,...
            'neckLengthC7Fm',   11.4,...
            'neckLengthSnFm',   18.2,...
            'neckCircumference',32,...
            'neckWidth',        10.8,...
            'neckDepth',        9.8,...
            'sex',              'f');            

    case 27 
        participantData = struct(...
            'id',               participantId,...              
            'age',              27,...
            'height',           1.64,...
            'weight',           56,...
            'headCircumference',55,...
            'headWidth',        14.6,...
            'headDepth',        19,...
            'headHeight',       19.3,...
            'neckLengthC7Fm',   10.6,...
            'neckLengthSnFm',   17.5,...
            'neckCircumference',31.8,...
            'neckWidth',        10.5,...
            'neckDepth',        9.8,...
            'sex',              'f');

    case 28 
        participantData = struct(...
            'id',               participantId,...              
            'age',              35,...
            'height',           1.82,...
            'weight',           69,...
            'headCircumference',58,...
            'headWidth',        16.4,...
            'headDepth',        19.7,...
            'headHeight',       20.3,...
            'neckLengthC7Fm',   10.8,...
            'neckLengthSnFm',   20.2,...
            'neckCircumference',36,...
            'neckWidth',        11.9,...
            'neckDepth',        11,...
            'sex',              'm');   
    otherwise
        assert(0, ['Error: particpantId is not within the range of 1-28,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end