function participantCarData=...
     getParticipantCarDataFebruary2023(participantId)


participantCarData = [];
participantCarData.biopacProblems = [];
participantCarData.ignoreTheseFileNumbers = [];

%If the notes mention EMG problems, please enter these problems into the 
%biopacProblemsStruct like this:
%
% Trial 11 has EMG problems on channels 2 and 3
% Trial 12 has EMG problems on channels 1
%
% We have 2 problematic trials, so we need an array of 2 biopacProblemsStruct:
%
%       biopacProblemsStruct(2) = struct('trialNumber',0,'channels',[]);
%
% And we fill out the struct like this
%
%       biopacProblemsStruct(1).trialNumber = 11;
%       biopacProblemsStruct(1).channels    = [2,3];
%       biopacProblemsStruct(2).trialNumber = 12;
%       biopacProblemsStruct(2).channels    = [1];
%
% Then we put this information into the participant struct like this:
%
%       participantCarData.biopacProblems = biopacProblemsStruct;
%





switch participantId
    case 1
        participantCarData.id           = participantId;

        participantCarData.condition       = {'nominal'; ...
                                              'nominal';...
                                              'seatBack'};

        %From the back of the hand-written paper sheet
        participantCarData.block           = {'headRom';...
                                              'A';...
                                              'B'};

        %These are the start and end file numbers for each of the
        %the conditions listed above
        participantCarData.blockFileNumbers = [8, 8;...
                                               9, 20;...
                                               21,27];

        %If the notes mention to ignore a trial that is within
        %the range in conditionFileNumbers, list them here.                                          
        participantCarData.ignoreTheseFileNumbers = [];                                           


    case 2
        participantCarData.id               = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};   

        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 33, 33;...
                                                34, 45;...
                                                46, 53];
        participantCarData.ignoreTheseFileNumbers = [];
        
    case 3
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 57, 57;...
                                                58, 69;...
                                                70, 77];
        participantCarData.ignoreTheseFileNumbers = [];

    case 4
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 80, 80;...
                                                81, 92;...
                                                93, 100];
        participantCarData.ignoreTheseFileNumbers = [];

    case 5
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 104, 104;...
                                                105, 116;...
                                                117, 124];
        participantCarData.ignoreTheseFileNumbers = [];

    case 6
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 128, 128;...
                                                129, 140;...
                                                141, 148];
        participantCarData.ignoreTheseFileNumbers = [];

    case 7 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 1, 1;...
                                                10, 21;...
                                                22, 29];
        participantCarData.ignoreTheseFileNumbers = [];

    case 8 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 31, 31;...
                                                33, 44;...
                                                45, 52];
        participantCarData.ignoreTheseFileNumbers = [];

    case 9
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 55, 55;...
                                                57, 68;...
                                                69, 76];
        participantCarData.ignoreTheseFileNumbers = [];


    case 10   
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 79, 79;...
                                                81, 92;...
                                                93, 100];
        participantCarData.ignoreTheseFileNumbers = [];

    case 11
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 102, 102;...
                                                104, 115;...
                                                116, 123];
        participantCarData.ignoreTheseFileNumbers = [];

    case 12
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 125, 125;...
                                                127, 138;...
                                                139, 146];
        participantCarData.ignoreTheseFileNumbers = [];

    case 13 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 1, 1;...
                                                3, 14;...
                                                15, 22];
        participantCarData.ignoreTheseFileNumbers = [];

    case 14 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 25, 25;...
                                                27, 38;...
                                                39, 46];
        participantCarData.ignoreTheseFileNumbers = [];

    case 15 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 49, 49;...
                                                51, 62;...
                                                63, 70];
        participantCarData.ignoreTheseFileNumbers = [];
    case 16 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 73, 73;...
                                                75, 86;...
                                                87, 94];
        participantCarData.ignoreTheseFileNumbers = [];
    case 17 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 97, 97;...
                                                99, 110;...
                                                111, 118];
        participantCarData.ignoreTheseFileNumbers = [];


    case 18 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 121, 121;...
                                                123, 134;...
                                                135, 142];
        participantCarData.ignoreTheseFileNumbers = [];

    case 19 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 3, 3;...
                                                5, 16;...
                                                17, 24];
        participantCarData.ignoreTheseFileNumbers = [];

    case 20 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 27, 27;...
                                                29, 40;...
                                                41, 48];
        participantCarData.ignoreTheseFileNumbers = [];
    case 21
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 50, 50;...
                                                52, 63;...
                                                64, 71];
        participantCarData.ignoreTheseFileNumbers = [];

    case 22
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 73, 73;...
                                                75, 86;...
                                                87, 94];
        participantCarData.ignoreTheseFileNumbers = [];

    case 23 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 95, 95;...
                                                97, 108;...
                                                109, 116];
        participantCarData.ignoreTheseFileNumbers = [];

    case 24 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 119, 119;...
                                                121, 132;...
                                                133, 140];
        participantCarData.ignoreTheseFileNumbers = [];

    case 25 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 2, 2;...
                                                4, 15;...
                                                16, 23];
        participantCarData.ignoreTheseFileNumbers = [];

    case 26 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'D'};
        participantCarData.blockFileNumbers = [ 24, 24;...
                                                26, 37;...
                                                38, 45];
        participantCarData.ignoreTheseFileNumbers = [];


    case 27 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'A';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 46, 46;...
                                                48, 59;...
                                                60, 67];
        participantCarData.ignoreTheseFileNumbers = [];
    case 28 
        participantCarData.id           = participantId;
        participantCarData.condition        = { 'nominal'; ...
                                                'nominal';...
                                                'seatBack'};        
        participantCarData.block            = { 'headRom';...
                                                'C';...
                                                'B'};
        participantCarData.blockFileNumbers = [ 69, 69;...
                                                71, 82;...
                                                83, 90];
        participantCarData.ignoreTheseFileNumbers = [];

   otherwise
        assert(0, ['Error: particpantId is not within the range of 1-28,',...
            ' or the information for the requested participant has ',...
            'not yet been entered']);
end