participantInfo = struct(...
    'id',               1,...
    'age',              20,...
    'height',           1.66,...
    'weight',           60,...
    'headCircumference',59,...
    'headWidth',        15.3,...
    'headDepth',        19.2,...
    'headHeight',       20.7,...
    'neckLengthC7Fm',   12.9,...
    'neckLengthSnFm',   18,...
    'neckCircumference',36.7,...
    'neckWidth',        11,...
    'neckDepth',        10.6,...
    'sex',              'm');
