participantInfo = struct(...
    'id',               5,...            
    'age',              32,...
    'height',           1.74,...
    'weight',           72,...
    'headCircumference',57,...
    'headWidth',        15.4,...
    'headDepth',        19.5,...
    'headHeight',       18.6,...
    'neckLengthC7Fm',   9.2,...
    'neckLengthSnFm',   15.6,...
    'neckCircumference',38.0,...
    'neckWidth',        10.7,...
    'neckDepth',        10.6,...
    'sex',              'm');
