participantInfo = struct(...
    'id',               9,...              
    'age',              22,...
    'height',           1.85,...
    'weight',           75,...
    'headCircumference',56.5,...
    'headWidth',        14.8,...
    'headDepth',        18.1,...
    'headHeight',       20.6,...
    'neckLengthC7Fm',   12.3,...
    'neckLengthSnFm',   18.9,...
    'neckCircumference',39.0,...
    'neckWidth',        10.9,...
    'neckDepth',        11,...
    'sex',              'm');
