participantInfo = struct(...
    'id',               10,...              
    'age',              22,...
    'height',           1.80,...
    'weight',           85,...
    'headCircumference',61,...
    'headWidth',        16,...
    'headDepth',        21,...
    'headHeight',       22.1,...
    'neckLengthC7Fm',   13,...
    'neckLengthSnFm',   20,...
    'neckCircumference',40.8,...
    'neckWidth',        12.3,...
    'neckDepth',        12.1,...
    'sex',              'm');
