participantInfo = struct(...
    'id',               8,...              
    'age',              21,...
    'height',           1.76,...
    'weight',           70,...
    'headCircumference',55.5,...
    'headWidth',        15.1,...
    'headDepth',        19.5,...
    'headHeight',       20,...
    'neckLengthC7Fm',   13,...
    'neckLengthSnFm',   19.4,...
    'neckCircumference',36.5,...
    'neckWidth',        11.6,...
    'neckDepth',        10.4,...
    'sex',              'm');
