participantInfo = struct(...
    'id',               2,...
    'age',              24,...
    'height',           1.72,...
    'weight',           60,...
    'headCircumference',57.5,...
    'headWidth',        15.5,...
    'headDepth',        19.4,...
    'headHeight',       18.6,...
    'neckLengthC7Fm',   13.2,...
    'neckLengthSnFm',   16.5,...
    'neckCircumference',30.6,...
    'neckWidth',        10.4,...
    'neckDepth',        9.3,...
    'sex',              'f');
