participantInfo = struct(...
    'id',               3,...            
    'age',              31,...
    'height',           1.84,...
    'weight',           86,...
    'headCircumference',58,...
    'headWidth',        15.9,...
    'headDepth',        19.8,...
    'headHeight',       19.8,...
    'neckLengthC7Fm',   9.4,...
    'neckLengthSnFm',   19.1,...
    'neckCircumference',38.0,...
    'neckWidth',        11.9,...
    'neckDepth',        12.1,...
    'sex',              'm');
